services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - nginx
    volumes:
      - v-nginx:/usr/share/nginx/html

  linux:
    image: centos:latest
    ports:
      - "8081-8082:81-82" #range port.
    networks:
      - nginx
      - centos  

volumes:
  v-nginx:


networks:
  nginx:
    driver: bridge
    attachable: true
  centos:
    driver: bridge
    attachable: true
