services:
  web:
    image: kubedevio/rotten-potatoes:v1
    ports:
      - 8080:5000
    networks:
      - prometheus
    depends_on:
      - mongodb
    environment:
      MONGODB: "admin"
      MONGODB_HOST: "mongodb"
      MONGO_PORT: "27017"
      MONGO_USERNAME: "mongouser"
      MONGO_PASSWORD: "mongopwd"
  
  mongodb:
    image: mongo:7.0
    volumes:
      - db_mongo:\\wsl.localhost\Ubuntu\app\db
    networks:
      - prometheus
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    
  prometheus:
    image: prom/prometheus:v2.47.2
    ports:
      - 9090:9090
    networks:
      - prometheus
    volumes:
      - ./prometheus.yaml:\\wsl.localhost\Ubuntu\home\caio\app\prometheus.yml
    
  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - 3000:3000
    networks:
      - prometheus

volumes:
  db_mongo:
networks:
  prometheus:
    driver: bridge