version: '3.8'

services:

  ghost:
    image: ghost:5-alpine
#    restart: always
    ports:
      - 8080:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ctGWi8AGFB9#99B@oafzF
      database__connection__database: ghost
    volumes:
      - ghost:/var/lib/ghost/content # name:/container-path
    networks:
      - public
      - private
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ctGWi8AGFB9#99B@oafzF
    volumes:
      - db:/var/lib/mysql
    networks:
      - private

volumes:
  ghost:
  db:

networks:
  public:
  private: